Repository betaflight/blackbox-log-viewer, pull requests merged in 2019-11, with the labels that each got.

#398 Updated version of NW.js.
  gulpfile.js
Labels: RN: BUGFIX

#399 adjust width of workspace-panel
  css/main.css
Labels: RN: BUGFIX

#402 Fixed file formats.
  assets/windows/installer.nsi
  images/cf_logo_white.svg
  js/graph_spectrum_calc.js
  js/graph_spectrum_plot.js
Labels: cleanup

#403 Add SonarCloud analysis file
  .sonarcloud.properties
Labels: build system improvement

#404 Add nightlies, Travis, Azure and Sonar to the README
  README.md
Labels: documentation update

#405 Clean and refactor graph_spectrum_plot.js
  js/graph_spectrum_plot.js
Labels: RN: REFACTORING

#410 Disabled Azure builds on pull requests.
  azure-pipelines.yml
Labels: build system improvement

#411 Save graph config on reorder by drag and drop.
  js/graph_legend.js
Labels: RN: BUGFIX

#408 Setting to show/hide background gradient off graph.
  index.html
  js/grapher.js
  js/user_settings_dialog.js
Labels: RN: IMPROVEMENT

#416 Add PID Error VS Setpoint graph to the analyser
  css/main.css
  index.html
  js/graph_spectrum.js
  js/graph_spectrum_calc.js
  js/graph_spectrum_plot.js
Labels: RN: IMPROVEMENT
