Repository betaflight/blackbox-log-viewer, pull requests merged in 2019-06, with the labels that each got.

#346 Better user experience using the Spectrum zoom
  js/graph_spectrum.js
Labels: RN: IMPROVEMENT

#347 Add limits to the calculated field PID SUM
  js/flightlog.js
Labels: RN: BUGFIX

#348 Little fixes to the help page
  css/keys_dialog.css
  index.html
Labels: RN: BUGFIX

#350 Updated the Chrome Web Store URL for the ChromeOS only version.
  README.md
Labels: housekeeping
