Repository betaflight/blackbox-log-viewer, pull requests merged in 2019-05, with the labels that each got.

#321 Fixed invalid pathing in RPM build.
  gulpfile.js
Labels: RN: BUGFIX

#323 Fix samples overflow in Spectrum
  js/graph_spectrum.js
Labels: RN: BUGFIX

#322 Added Frequency vs Throttle Spectrum Graph
  css/main.css
  index.html
  js/graph_spectrum.js
  js/graph_spectrum_plot.js
Labels: RN: IMPROVEMENT

#324 Moved from 'npm' to 'yarn'.
  .travis.yml
  README.md
  gulpfile.js
  package-lock.json
  package.json
  yarn.lock
Labels: RN: IMPROVEMENT

#328 Added devDependency on 'yarn' to enable production build.
  package.json
  yarn.lock
Labels: RN: IMPROVEMENT, fixes broken build

#330 Fix label of Spectrum when changing the workspace page
  js/grapher.js
Labels: RN: BUGFIX

#331 Add numeric interpretation of RSSI
  js/flightlog_fields_presenter.js
  js/graph_config.js
Labels: RN: IMPROVEMENT

#332 Draw filters and others over Frequency vs Throttle Spectrum
  css/main.css
  index.html
  js/graph_spectrum.js
  js/graph_spectrum_plot.js
Labels: RN: IMPROVEMENT

#337 Fixed yarn production install.
  gulpfile.js
  package.json
  yarn.lock
Labels: RN: BUGFIX

#341 Fix selection of filters over spectrum
  js/graph_spectrum.js
Labels: RN: BUGFIX

#342 Add type of filter to the spectrum labels
  js/graph_spectrum_plot.js
Labels: RN: IMPROVEMENT

#345 Update stale / no-response bot configurations.
  .github/no-response.yml
Labels: householding
