Repository betaflight/blackbox-log-viewer, pull requests merged in 2019-10, with the labels that each got.

#374 Add debug names for Betaflight 4.1
  js/flightlog_fielddefs.js
  js/flightlog_fields_presenter.js
Labels: RN: IMPROVEMENT

#376 Add RPM Filter info to the Header
  index.html
  js/flightlog_parser.js
  js/header_dialog.js
Labels: RN: IMPROVEMENT, needs coordination with betaflight

#371 Added unified '.gitattributes' file.
  .gitattributes
Labels: housekeeping

#375 Add Iterm relax fields to header
  index.html
  js/flightlog_fielddefs.js
  js/flightlog_parser.js
  js/header_dialog.js
Labels: RN: IMPROVEMENT

#370 Added changelog for 3.4.0.
  changelog.html
Labels: housekeeping

#378 Add Dyn Notch info to Header
  index.html
  js/flightlog_fielddefs.js
  js/flightlog_parser.js
  js/header_dialog.js
Labels: RN: IMPROVEMENT

#379 Added note about security settings workaround for MacOS X to README.md.
  README.md
Labels: documentation update

#382 Added a 'gulp release' task to package.json.
  package.json
Labels: build system improvement

#384 Fix dyn notch range
  js/flightlog_fielddefs.js
Labels: RN: BUGFIX

#386 Add RTH and GPS_RESCUE_THROTTLE_PID variables to log file
  js/flightlog_fields_presenter.js
Labels: RN: IMPROVEMENT, testing required

#390 Feature: Workspace selection
  .jshintrc
  css/main.css
  gulpfile.js
  index.html
  js/main.js
  js/workspace_selection.js
Labels: RN: IMPROVEMENT

#392 Initial implementation of screenshot feature
  gulpfile.js
  index.html
  js/main.js
  js/screenshot.js
  package.json
  yarn.lock
Labels: RN: IMPROVEMENT

#393 Suggest a filename on the save screenshot dialog
  js/screenshot.js
Labels: RN: IMPROVEMENT
