Repository betaflight/blackbox-log-viewer, pull requests merged in 2020-08, with the labels that each got.

#461 Refactor application association in registry
  assets/windows/installer.iss
Labels: RN: IMPROVEMENT

#462 Fix open window association with --disable-features=nw2
  js/main.js
Labels: RN: BUGFIX

#463 Move WebMWriter library to node_modules
  gulpfile.js
  index.html
  js/vendor/webm-writer-0.1.1.js
  package.json
  yarn.lock
Labels: RN: IMPROVEMENT

#464 Incremented version to 3.6.0
  manifest.json
  package.json
Labels: housekeeping

#465 Added vbat_sag_compensation to header
  index.html
  js/flightlog_parser.js
  js/header_dialog.js
Labels: RN: IMPROVEMENT
