Repository betaflight/blackbox-log-viewer, pull requests merged in 2020-03, with the labels that each got.

#432 Updated documentation from template repository.
  .github/issue_template.md
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
Labels: documentation update

#433 Added 'debug-release' gulp target, and made the Azure build default to it.
  assets/windows/installer.nsi
  azure-pipelines.yml
  gulpfile.js
Labels: build system improvement

#435 Fixed Azure build.
  azure-pipelines.yml
Labels: build system improvement

#436 Fix fade header
  css/bootstrap-theme.css
  css/bootstrap-theme.css.map
  css/bootstrap-theme.min.css
  css/bootstrap.css
  css/bootstrap.css.map
  css/bootstrap.min.css
  fonts/glyphicons-halflings-regular.eot
  fonts/glyphicons-halflings-regular.svg
  fonts/glyphicons-halflings-regular.ttf
  fonts/glyphicons-halflings-regular.woff
  fonts/glyphicons-halflings-regular.woff2
  gulpfile.js
  index.html
  js/header_dialog.js
  js/vendor/bootstrap.js
  js/vendor/bootstrap.min.js
  js/vendor/npm.js
  package.json
  yarn.lock
Labels: RN: BUGFIX

#437 Fixed release builds for Windows. Also made the build scripts throw an error on NSIS failures.
  assets/windows/installer.nsi
  gulpfile.js
Labels: RN: BUGFIX, fixes broken build
