Repository betaflight/blackbox-log-viewer, pull requests merged in 2020-10, with the labels that each got.

#474 Remove Chrome support
  .gitignore
  .travis.yml
  Makefile
  README.md
  chromeBackground.js
  gulpfile.js
  index.js
  js/main.js
  js/tools.js
  manifest.json
Labels: RN: IMPROVEMENT

#475 Add latest version and license badges to readme
  README.md
Labels: documentation update

#476 Improving Betaflight logo
  css/main.css
  images/light-wide-2.svg
Labels: RN: IMPROVEMENT

#478 Restrict Windows version to Windows 8 or higher
  README.md
  assets/windows/installer.iss
Labels: RN: IMPROVEMENT, documentation update, requires entry in release notes

#472 Show the limit in motors graph
  js/flightlog.js
  js/flightlog_fielddefs.js
  js/flightlog_fields_presenter.js
  js/flightlog_parser.js
  js/graph_config.js
Labels: RN: IMPROVEMENT

#480 Display selected gyro header value
  index.html
  js/flightlog_fielddefs.js
  js/flightlog_parser.js
  js/header_dialog.js
Labels: RN: IMPROVEMENT, needs coordination with betaflight
