Repository betaflight/blackbox-log-viewer, pull requests merged in 2021-09, with the labels that each got.

#528 Remove unneeded file.
  images/bf_logo_white.svg
Labels: cleanup, RN: REFACTORING, Tested

#515 Fix rounding in setpoint vs error graph
  js/graph_spectrum_plot.js
Labels: RN: BUGFIX, Tested

#520 Fix DUAL_GYRO_SCALED debug mode graph
  js/graph_config.js
Labels: RN: BUGFIX, Tested

#526 Add motor poles support
  index.html
  js/flightlog_fields_presenter.js
  js/flightlog_parser.js
  js/header_dialog.js
Labels: RN: IMPROVEMENT

#512 Updates to log viewer for 4.3
  index.html
  js/flightlog_fielddefs.js
  js/flightlog_parser.js
  js/header_dialog.js
Labels: RN: IMPROVEMENT, Tested
