Repository betaflight/blackbox-log-viewer, pull requests merged in 2022-12, with the labels that each got.

#613 Added map with home position / craft position / flight trail #490
  .gitignore
  css/main.css
  images/markers/craft.png
  images/markers/home.png
  index.html
  js/flightlog.js
  js/graph_map.js
  js/main.js
  js/user_settings_dialog.js
  package.json
  yarn.lock
Labels: RN: IMPROVEMENT, Tested

#616 Make measurement system units changeable.
  index.html
  js/flightlog_fields_presenter.js
  js/user_settings_dialog.js
Labels: RN: IMPROVEMENT

#618 fixed NaN validation, add no-gps-data class to map
  css/main.css
  js/graph_map.js
Labels: RN: BUGFIX

#621 Fix nightly build badge
  README.md
Labels: bugfix, housekeeping

#622 Add support for Omron 2SMBP-02B barometer
  js/flightlog_fielddefs.js
Labels: RN: IMPROVEMENT
