Repository betaflight/blackbox-log-viewer, pull requests merged in 2022-11, with the labels that each got.

#605 Add GPS DOP debug
  js/flightlog_fields_presenter.js
Labels: RN: IMPROVEMENT, Ready to merge

#607 Update debug mode
  js/flightlog_fielddefs.js
Labels: RN: BUGFIX

#606 Allow for GPS Data in Table/Graph/Exports
  js/flightlog.js
  js/flightlog_fields_presenter.js
  js/flightlog_index.js
  js/graph_config.js
  js/main.js
Labels: RN: IMPROVEMENT, RN: BUGFIX, Tested

#609 Fix debug modes
  js/flightlog_fielddefs.js
  js/flightlog_fields_presenter.js
  js/graph_config.js
  js/grapher.js
Labels: RN: BUGFIX, Tested

#610 Fix typos
  CONTRIBUTING.md
  README.md
  changelog.html
  css/header_dialog.css
  index.html
  js/cache.js
  js/datastream.js
  js/flightlog_parser.js
  js/graph_config_dialog.js
  js/grapher.js
  js/gui.js
  js/header_dialog.js
  js/main.js
  js/tools.js
Labels: cleanup
