Repository betaflight/blackbox-log-viewer, pull requests merged in 2022-01, with the labels that each got.

#551 D Min -> D Max in html
  index.html
Labels: Tested, Ready to merge

#555 fix typo in index.html
  index.html
Labels: Ready to merge

#557 fix name of setpoint trace in feedforward debug
  js/flightlog_fields_presenter.js
Labels: bugfix, Ready to merge

#516 Temporary remove FileWriter support when exporting video
  js/flightlog_video_renderer.js
Labels: pinned, RN: BUGFIX, Tested

#559 Revert "Temporary remove FileWriter support when exporting video"
  js/flightlog_video_renderer.js
Labels: cleanup

#554 Update FFT debug modes
  js/flightlog_fields_presenter.js
  js/graph_config.js
  js/header_dialog.js
Labels: RN: IMPROVEMENT

#562 Move issues to Github forms
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: housekeeping

#495 chore: use node 14
  .nvmrc
  .travis.yml
  azure-pipelines.yml
  gulp-appdmg.js
  gulpfile.js
  package.json
  yarn.lock
Labels: RN: IMPROVEMENT

#563 Add portable build to Windows
  assets/windows/installer.iss
  gulpfile.js
Labels: build system improvement
