Repository betaflight/blackbox-log-viewer, pull requests merged in 2022-09, with the labels that each got.

#596 zoom control 200px wide to increase accuracy
  css/main.css
Labels: enhancement

#598 hotfix for latest master
  js/flightlog_fields_presenter.js
Labels: bugfix

#599 chore - fix sonar issues
  js/flightlog_fields_presenter.js
Labels: RN: REFACTORING
