Repository betaflight/blackbox-log-viewer, pull requests merged in 2022-06, with the labels that each got.

#560 Blackbox increase resolution on setpoint, gyro and rounding
  js/flightlog_fielddefs.js
  js/flightlog_fields_presenter.js
  js/flightlog_parser.js
  js/graph_config.js
  js/sticks.js
Labels: Inactive

#581 Add artifact links to PRs
  .github/workflows/artifact-links.yml
  .github/workflows/hide-artifact-links.yml
Labels: build system improvement

#575 Upgrade NwBuilder to version 3.7.4
  package.json
  yarn.lock
Labels: build system improvement

#580 Update workflows to use Ubuntu-22.04
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: build system improvement

#586 fix issue #425 -- fix export video stuck calculating if craft/stick size = 0
  js/flightlog_video_renderer.js
Labels: bugfix
