Repository betaflight/blackbox-log-viewer, pull requests merged in 2023-12, with the labels that each got.

#669 Update dependencies
  package.json
  yarn.lock
Labels: dependencies

#672 Fix macos-alias
  .github/workflows/ci.yml
Labels: dependencies

#670 Added thrust_linear
  js/flightlog_parser.js
Labels: RN: IMPROVEMENT

#671 Add missing debugs
  js/flightlog_fielddefs.js
  js/flightlog_fields_presenter.js
  js/graph_config.js
Labels: RN: IMPROVEMENT, Tested

#657 Added tpa lower parameters to header
  js/flightlog_parser.js
Labels: needs coordination with betaflight, RN: IMPROVEMENT

#673 Update Node.js
  .nvmrc
  package.json
Labels: dependencies

#675 Add LSM6DSV16X
  js/flightlog_fielddefs.js
Labels: RN: IMPROVEMENT

#677 Update tpa_low
  js/flightlog_parser.js
Labels: RN: REFACTORING

#676 Add EZLANDING debug
  js/flightlog_fielddefs.js
  js/flightlog_fields_presenter.js
  js/flightlog_parser.js
Labels: RN: IMPROVEMENT

#678 Update flightlog_fields_presenter.js
  js/flightlog_fields_presenter.js
Labels: enhancement
