Repository betaflight/blackbox-log-viewer, pull requests merged in 2023-10, with the labels that each got.

#655 header fixes for antigravity
  index.html
  js/flightlog_parser.js
  js/header_dialog.js
Labels: RN: BUGFIX

#660 Replace non valid values with NaN instead of "" in csv export
  js/webworkers/csv-export-worker.js
Labels: bugfix

#662 Fix handling of missing G frame
  js/flightlog.js
Labels: bugfix

#664 Toggle trace/field visibility
  css/main.css
  js/graph_config.js
  js/graph_legend.js
  js/grapher.js
Labels: RN: IMPROVEMENT
