Repository betaflight/blackbox-log-viewer, pull requests merged in 2024-11, with the labels that each got.

#787 Resolved issue of compas (mag_adc[]) curves
  src/flightlog_fields_presenter.js
Labels: RN: BUGFIX

#791 Update ATTITUDE debug
  src/flightlog_fields_presenter.js
  src/graph_config.js
Labels: RN: IMPROVEMENT

#789 Added curves settings for axis_s log fields (for airplanes)
  src/flightlog_fields_presenter.js
Labels: RN: IMPROVEMENT

#790 Added computing of heading[] fields from new flight attitude quatrernion log data
  src/flightlog.js
Labels: needs coordination with betaflight, RN: IMPROVEMENT

#796 Add missing debug modes
  src/flightlog_fielddefs.js
  src/flightlog_fields_presenter.js
Labels: RN: IMPROVEMENT

#797 Resolved issues of show motor_idle and motors Start inc header fields for BF 4.6 log files
  index.html
  src/flightlog_parser.js
  src/header_dialog.js
Labels: RN: IMPROVEMENT
