Repository betaflight/blackbox-log-viewer, pull requests merged in 2024-05, with the labels that each got.

#739 Give a more clear name under Mobile to the PWA app
  package.json
  vite.config.js
Labels: housekeeping

#741 Remove changelog
  changelog.html
  index.html
  src/css/main.css
  src/main.js
Labels: housekeeping

#742 Add nightly PWA link to the README
  README.md
Labels: housekeeping

#749 Associate .bbl and .bfl files with PWA
  src/main.js
  vite.config.js
Labels: RN: IMPROVEMENT

#747 Auto fill of curves table by selecting group curves names on Chart setup dialog box
  src/graph_config.js
  src/graph_config_dialog.js
  src/main.js
Labels: RN: IMPROVEMENT

#745 Restore various default workspaces by using menu
  index.html
  src/main.js
  src/workspace_menu.js
  src/ws_ctzsnooze.json
  src/ws_supafly.json
Labels: RN: IMPROVEMENT

#750 add dyn_idle_start_increase parameter to header view
  index.html
  src/flightlog_parser.js
  src/header_dialog.js
Labels: RN: IMPROVEMENT

#752 Fix error by loading default workspace, addition to #751
  src/main.js
  src/workspace-supafly.json
  src/workspaces-ctzsnooze.json
Labels: RN: BUGFIX
