Repository betaflight/blackbox-log-viewer, pull requests merged in 2024-03, with the labels that each got.

#712 Scale and display EZLANDING debug fields as percentages
  js/flightlog_fields_presenter.js
  js/graph_config.js
Labels: RN: IMPROVEMENT

#714 Header: fix voltage scale
  js/header_dialog.js
Labels: RN: BUGFIX

#713 Resolved issue of wrong throttle values at spectrum chart when not all log parameters are selected in blackbox settings
  js/flightlog.js
Labels: RN: BUGFIX

#715 Added warning at the status bar while actual log rate is less then required
  css/main.css
  index.html
  js/graph_spectrum_calc.js
Labels: RN: IMPROVEMENT

#717 Reset analyserZoomX/Y state for new opened logs
  js/graph_spectrum_plot.js
Labels: bugfix

#720 Fix release assets upload
  .github/workflows/build-release.yml
Labels: housekeeping

#719 Add EZLANDING speed parameter debug fields
  js/flightlog_fields_presenter.js
Labels: RN: IMPROVEMENT
