Repository betaflight/blackbox-log-viewer, pull requests merged in 2024-10, with the labels that each got.

#774 The azimuth of Home point added as computed field
  src/flightlog.js
  src/flightlog_fields_presenter.js
  src/graph_config.js
Labels: RN: IMPROVEMENT

#775 rename d_min related values
  index.html
  src/flightlog_fielddefs.js
  src/flightlog_fields_presenter.js
  src/flightlog_parser.js
  src/graph_config.js
  src/header_dialog.js
Labels: RN: REFACTORING

#777 Fix export video
  src/main.js
Labels: RN: BUGFIX

#778 Add browser check
  src/main.js
  src/tools.js
Labels: RN: IMPROVEMENT

#779 Export of spectrum analyzer data to Csv file
  index.html
  public/js/webworkers/csv-export-worker.js
  public/js/webworkers/spectrum-export-worker.js
  src/css/main.css
  src/graph_spectrum.js
  src/main.js
  src/spectrum-exporter.js
Labels: RN: IMPROVEMENT

#780 Added spectrum comparison by using import spectrum data from CSV file
  index.html
  src/css/main.css
  src/graph_spectrum.js
  src/graph_spectrum_plot.js
  src/main.js
Labels: RN: IMPROVEMENT

#784 Deprecate gps-rescue-throttle-pid and replace with autopilot-altitude
  src/flightlog_fielddefs.js
  src/flightlog_fields_presenter.js
Labels: RN: IMPROVEMENT

#781 Remove gyro_scaled
  src/flightlog_fielddefs.js
Labels: RN: IMPROVEMENT
