Repository betaflight/blackbox-log-viewer, pull requests merged in 2024-01, with the labels that each got.

#681 Migrate hub to gh
  .github/workflows/build-release.yml
Labels: housekeeping

#686 Update gulp
  package.json
  yarn.lock
Labels: dependencies

#688 Update actions/cache in workflow
  .github/workflows/ci.yml
Labels: build system improvement

#693 Fixes #691 Prevent out of bounds access when ploting Throttle vs Frequency
  js/graph_spectrum_calc.js
Labels: bugfix, Tested
