Repository betaflight/blackbox-log-viewer, pull requests merged in 2025-05, with the labels that each got.

#822 Adding cloudflare preview builds
  .github/workflows/deploy-preview.yml
Labels: housekeeping

#820 Added power spectral density curves at the spectrum chart
  index.html
  src/graph_spectrum.js
  src/graph_spectrum_calc.js
  src/graph_spectrum_plot.js
Labels: RN: IMPROVEMENT

#826 Added Power Spectral Density curves at the spectrum chart (Completion of #820 PR)
  index.html
  src/graph_spectrum.js
  src/graph_spectrum_calc.js
  src/graph_spectrum_plot.js
Labels: RN: IMPROVEMENT

#830 Revert "Added Power Spectral Density curves at the spectrum chart (Completion of #820 PR)"
  index.html
  src/graph_spectrum.js
  src/graph_spectrum_calc.js
  src/graph_spectrum_plot.js
Labels: RN: BUGFIX

#834 fix preview checkout
  .github/workflows/deploy-preview.yml
Labels: housekeeping

#835 Create .coderabbit.yaml
  .coderabbit.yaml
Labels: housekeeping

#838 Revert "Bug fix: The spectrum graph is sometimes not displayed after change spectrums type"
  src/graph_spectrum.js
Labels: RN: BUGFIX

#839 Bug fix: The spectrum graph is sometimes not displayed after change s…
  src/graph_spectrum.js
  src/graph_spectrum_calc.js
Labels: RN: BUGFIX
