Repository betaflight/blackbox-log-viewer, pull requests merged in 2025-09, with the labels that each got.

#856 Resolved issue of mouse scrolling on Mozila firefox
  src/main.js
Labels: RN: BUGFIX

#857 Code improvements
  src/main.js
Labels: RN: REFACTORING

#860 Update app version
  package.json
Labels: housekeeping
