Repository betaflight/blackbox-log-viewer, pull requests merged in 2025-01, with the labels that each got.

#802 Update IMU (remove legacy)
  src/flightlog_fielddefs.js
Labels: RN: IMPROVEMENT

#806 Fix type error
  src/flightlog_fielddefs.js
Labels: RN: BUGFIX

#807 Add IMM42653
  src/flightlog_fielddefs.js
Labels: RN: IMPROVEMENT

#658 Added chirp parameters to header
  src/flightlog_parser.js
Labels: needs coordination with betaflight, RN: IMPROVEMENT

#810 Fix undefined video export dialog
  src/main.js
Labels: RN: BUGFIX
